sudo: true
services:
    - docker

before_install:
    - docker info
    - docker version

    - docker build  -f test/Dockerfile-ubuntu14.04      -t prometheus_trusty       .
    - docker build  -f test/Dockerfile-ubuntu12.04      -t prometheus_precise      .
    - docker build  -f test/Dockerfile-debian8          -t prometheus_jessie       .
    - docker build  -f test/Dockerfile-debian7          -t prometheus_wheezy       .
    - docker build  -f test/Dockerfile-centos7          -t prometheus_centos7      .
    - docker build  -f test/Dockerfile-centos6          -t prometheus_centos6      .
    - docker build  -f test/Dockerfile-ubuntu14.04-git  -t prometheus_trusty_git   .
    - docker build  -f test/Dockerfile-debian8-git      -t prometheus_jessie_git   .
    - docker build  -f test/Dockerfile-centos7-git      -t prometheus_centos7_git  .

script:
    - docker run  -v $(pwd):/data  prometheus_trusty
    - docker run  -v $(pwd):/data  prometheus_precise
    - docker run  -v $(pwd):/data  prometheus_jessie
    - docker run  -v $(pwd):/data  prometheus_wheezy
    - docker run  -v $(pwd):/data  prometheus_centos7
    - docker run  -v $(pwd):/data  prometheus_centos6
    - docker run  -v $(pwd):/data  prometheus_trusty_git
    - docker run  -v $(pwd):/data  prometheus_jessie_git
    - docker run  -v $(pwd):/data  prometheus_centos7_git

    - echo "==> Validating the test results..."
    - grep '^consul_up' result-ubuntu14.04
    - grep '^consul_up' result-ubuntu12.04
    - grep '^consul_up' result-centos7
    - grep '^consul_up' result-centos6
    - grep '^consul_up' result-debian8
    - grep '^consul_up' result-debian7
    - grep '^consul_up' result-ubuntu14.04-git
    - grep '^consul_up' result-centos7-git
    - grep '^consul_up' result-debian8-git



    # Consul role does not yet support Ubuntu 12.04
    # Consul role does not yet support centos6 or debian

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
