---
# file: handlers/main.yml
#

- name: restart consul_exporter
  service: name=consul_exporter state=restarted

- name: reload consul_exporter
  service: name=consul_exporter state=reloaded

- name: stop consul_exporter
  service: name=consul_exporter state=stopped
